FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY AlertrixAPI/AlertrixAPI.csproj AlertrixAPI/
RUN dotnet restore AlertrixAPI/AlertrixAPI.csproj

COPY . .
RUN dotnet publish AlertrixAPI/AlertrixAPI.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app

ENV ASPNETCORE_URLS=http://0.0.0.0:8080

COPY --from=build /app/publish .
EXPOSE 8080
ENTRYPOINT ["dotnet", "AlertrixAPI.dll"]
